### ISSUE TITLE
Other platforms like i386 amd64 ?

### ISSUE THREAD

**Issue by sp2ong** [nostar/md380_vocoder#1]
Hi 

on the pi-star forum, you wrote that this is for RPI but do you have any plans to run it on other platforms? I am currently using 2 computers i386 and amd64 for my local repeaters where I want add cross mode P252DMR. It will be nice to try use P252DMR on i386, amd64

but question it is work in way P25 ->DMR and DMR ->P25 ?

......
objcopy \
	-I binary md380fw.img \
	--change-addresses=0x0800C000 \
	--rename-section .data=.firmware \
	--add-symbol ambe_encode_thing=0x08050d91 \
	--add-symbol ambe_unpack=0x08048c9d \
	--add-symbol ambe_decode_wav=0x08051249 \
	-O elf32-littlearm -B arm firmware.o
objcopy: architecture arm unknown
Makefile:13: polecenia dla obiektu 'firmware.o' nie powiodły się
make: *** [firmware.o] Błąd 1

**Comment by nostar** [comment]
The md380 firmware from the md380tools projects is ARM firmware.  You must either run it on ARM hardware or an ARM emulator.

**Comment by sp2ong** [comment]
Ok
Clear, md380-emu I run on i386 platform use 

/usr/bin/qemu-arm-static /opt/md380-emu/md380-emu -S 2470

for this I must compile P252DMR on RPI and run P252DRM like this ?:

/usr/bin/qemu-arm-static /opt/bin/P252DMR /opt/P252DMR/P252DMR.ini 


> You must either run it on ARM hardware or an ARM emulator.
